[package]
name = "sisyphus"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
core = { workspace = true }
provider = { workspace = true }
tools = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
dotenv = "0.15"
rust-i18n = "3"
