[package]
name = "sisyphus"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
sisyphus_core = { workspace = true }
provider = { workspace = true }
tools = { workspace = true }
server = { path = "../server" }
client = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
dotenv = "0.15"
rust-i18n = "3"
reqwest-eventsource = "0.5"
futures = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
colored = "2.0"
reedline = "0.28"
ratatui = "0.26"
crossterm = { version = "0.27", features = ["event-stream"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
