[package]
name = "provider"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }

[features]
dev_debug = []

[dev-dependencies]
mockall.workspace = true
insta = "1.34"
wiremock = "0.6"
