[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
sisyphus_cli_core = { path = "../cli-core", package = "sisyphus-cli-core" }
common = { workspace = true }
sisyphus_core = { workspace = true }
provider = { workspace = true }
tools = { workspace = true }
server = { path = "../server" }
client = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
reqwest-eventsource = "0.6"
futures = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
colored = "2.0"
async-trait.workspace = true
rust-i18n = "3"
reedline = "0.28"
ratatui = "0.26"
crossterm = { version = "0.27", features = ["event-stream"] }
arboard = "3.6.1"

[features]
dev_debug = []
