[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
sisyphus_core = { workspace = true }
provider = { workspace = true }
tools = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }

axum = { version = "0.7", features = ["macros"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["cors", "trace", "fs"] }

[features]
dev_debug = []

[dev-dependencies]
async-trait = { workspace = true }
reqwest = { workspace = true }
tracing-subscriber = { workspace = true }
